name: build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: msys2/setup-msys2@v2
        with:
          msystem: clang64
          install: >-
            base-devel
            git
            mingw-w64-clang-x86_64-clang
            mingw-w64-clang-x86_64-cmake
            mingw-w64-clang-x86_64-ninja
            mingw-w64-clang-x86_64-mpv
          update: true
      - name: Build
        shell: msys2 {0}
        run: |
          export CFLAGS="-march=tigerlake -mprefer-vector-width=512 -O3 -flto=full -mguard=cf -fcf-protection=full -D_WIN32_WINNT=0x0A00 -DWINVER=0x0A00 -fvisibility=hidden -fvirtual-function-elimination -fwhole-program-vtables -fdata-sections -ffunction-sections -fno-unwind-tables -fno-asynchronous-unwind-tables -fomit-frame-pointer -fno-emulated-tls -pthread"
          export CXXFLAGS="$CFLAGS"
          export LDFLAGS="$CFLAGS -fuse-ld=lld -Wl,-s,-O3,--gc-sections,--icf=all,--no-insert-timestamp,--major-os-version=10,--major-subsystem-version=6,--minor-subsystem-version=2,--file-alignment=4096 -Xlinker -Xlink=-cetcompat -Xlinker -Xlink=-guard:cf,longjmp,ehcont -Xlinker -Xlink=-opt:lldlto=3 -Xlinker -Xlink=-opt:lldltocgo=3"
          mkdir build && cd build
          cmake -DCMAKE_BUILD_TYPE=RELEASE \
            -DCMAKE_SHARED_LINKER_FLAGS="-static" \
            -G Ninja ..
          cmake --build . --target package
      - uses: actions/upload-artifact@v4
        with:
          name: menu
          path: build/menu.zip
  publish:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' || github.ref_type == 'tag' }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
      - uses: rickstaa/action-create-tag@v1
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          tag: dev
          force_push_tag: true
      - uses: ncipollo/release-action@v1
        with:
          commit: ${{ github.sha }}
          tag: ${{ github.ref == 'refs/heads/main' && 'dev' || github.ref_name }}
          artifacts: "menu/menu.zip"
          allowUpdates: true
          prerelease: ${{ github.ref == 'refs/heads/main' }}
          name: ${{ github.ref == 'refs/heads/main' && 'dev' || github.ref_name }}
          body: |
            https://github.com/tsl0922/mpv-menu-plugin#installation
