name: build

on:
  push:
    branches: ["*"]
    pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: msys2/setup-msys2@v2
        with:
          msystem: mingw64
          install: >-
            base-devel
            git
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-ninja
            mingw-w64-x86_64-mpv
          update: true
      - name: Build
        shell: msys2 {0}
        run: |
          mkdir build && cd build
          cmake -DCMAKE_BUILD_TYPE=RELEASE -G Ninja ..
          cmake --build .
      - uses: actions/upload-artifact@v3
        with:
          name: menu
          path: build/menu.dll
  publish:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
      - name: Zip files
        run: zip -r menu.zip menu
      - uses: rickstaa/action-create-tag@v1
        with:
          tag: dev
          force_push_tag: true
      - uses: ncipollo/release-action@v1
        with:
          commit: ${{ github.sha }}
          tag: dev
          artifacts: "menu.zip"
          allowUpdates: true
          prerelease: true
          name: Dev build
          body: Development build